version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: # forward to host port (localhost)
        - 5000:5000
    env_file:
        - ./api/environments/local.env
    restart: always
    volumes:
        - ./api:/api
    container_name: flask_api